name: Retrieve Access Token

on:
  schedule:
    - cron: '0 0 1 * *' # Run the workflow at midnight on the first day of every month

jobs:
  retrieve-access-token:
    runs-on: ubuntu-latest

    steps:
      - name: Send HTTP POST request to Google Apps Script
        run: |
          # Replace 'YOUR_WEB_APP_URL' with the URL of your Google Apps Script web app endpoint
          response=$(curl -X POST -H "Content-Type: application/json" -d '{"data": "your_data"}' YOUR_WEB_APP_URL)
          echo "$response" # Print the response for debugging purposes
          access_token=$(echo "$response" | jq -r '.token') # Extract the access token from the response using 'jq' tool
          echo "::set-output name=ACCESS_TOKEN::$access_token" # Set the access token as an output variable

      - name: Save Access Token as GitHub Secret
        if: ${{ success() }}
        run: echo "ACCESS_TOKEN=$ACCESS_TOKEN" >> $GITHUB_ENV
